#' Create an OAuth Shiny Client
#'
#' The OAuth Shiny Client object allows you to use an oauth client in a shiny
#' application and supports two scenarios: (i) Restricting access to a shiny
#' application and (ii) performing actions on behalf of the user (behind an open
#' or restricted shiny application). If the OAuth Provider follows the [OpenID
#' specification](https://openid.net/specs/openid-connect-core-1_0.html) , the
#' `openid_issuer_url` can be used to retrieve endpoints and keys to perform and
#' verify the OAuth dance. If the provider does not support OpenID (e.g.
#' Github), then the user needs to figure this out on its own and provide
#' necessary endpoints (e.g `auth_url` and `token_url`) themselves.
#'
#' @param name The name of the OAuth Provider. Used to provide an easy reference
#'   to the client. Also used to derive the name of the login-endpoint (e.g.
#'   /login/github), client cookie name (e.g. oauth_app_github_token). Should be
#'   a valid URI path.
#' @param id Client identifier
#' @param secret Client secret. For most apps, this is technically confidential
#'   so in principle you should avoid storing it in source code. However, many
#'   APIs require it in order to provide a user friendly authentication
#'   experience, and the risks of including it are usually low. To make things a
#'   little safer, I recommend using [obfuscate()] when recording the client
#'   secret in public code.
#' @param auth_url Authorization url. If the client does not follow the OpenID
#'   specification you'll need to discover this by reading the documentation.
#'   Otherwise, you could supply the `openid_issuer_url`. Supplying an
#'   `auth_url` will take precedence over any urls discovered by
#'   `openid_issuer_url`.
#' @param token_url Url to retrieve an access token.
#' @param redirect_uri URL to redirect back to after authorization is complete.
#'   Often this must be registered with the API in advance.
#' @param openid_issuer_url If the provider follows the openid specification,
#'   provide the issuer url. Do not include the path to the configuration
#'   endpoint (also known as Well-Known Configuration Endpoint). Examples
#'   include
#'   `https://login.microsoftonline.com/TENANT/v2.0`
#'   (microsoft) and `https://accounts.google.com/` (google).
#' @param openid_claims Character vector of claims to be retrieved if
#' `openid_issuer_url` is not NULL. These claims will be included in the app
#' token to easily retrieve user information in shiny. Defaults to `name`,
#' `email`, `aud` and `sub`. See Section 5.1. Standard Claims of
#' [OpenID spec](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims).
#' @param scope Scopes to be requested from the resource owner.
#' @param auth_params A list containing additional parameters passed to
#'   [oauth_flow_auth_code_url()].
#' @param token_params List containing additional parameters passed to the
#'   `token_url`.
#' @param pkce Use "Proof Key for Code Exchange"? This adds an extra layer of
#'   security and should always be used if supported by the server.
#' @param postprocess_token A custom function for postprocessing the token, e.g.
#'   token exchange or verification
#' @param auth_provider Whether the OAuth client should be used to restrict
#'   access to the shiny application. An OAuth App could often have multiple
#'   auth providers (e.g. Apple, and Google), sometimes described as "social
#'   login". If set to `TRUE`, this will generate login buttons for the client
#'   when the standard UIs for login (`oauth_shiny_ui_login()`) and logout are
#'   used. If set to `FALSE`, the OAuth Client is not used to restrict access to
#'   the app, but could still be used to perform actions against the OAuth
#'   provider when the user has succesfully logged in to the application.
#' @param auth_provider_primary If the user has a preferred provider, this
#'   could be used to automatically redirect the user to follow the OAuth dance
#'   without displaying a UI for logigng in. A typical scenario could be an
#'   enterprise application where the a non authorized user is always redirected
#'   to login at a single identity provider (e.g. Microsoft Entra). Set
#'   `login_ui` to NULL to enable direct login
#' @param auth_set_custom_claim If the OAuth provider does not follow the
#'   openid specification, a custom function could be used to set the audience
#'   (aud) and subject (sub) for the app token. This function should take
#'   `client` and `token` as input arguments. See
#'   `oauth_shiny_client_github_set_custom_claim()`
#' @param login_button A button typically generated by
#'   `oauth_shiny_ui_button` which can be used in the login UI
#' @param login_button_dark A button typically generated by
#'   `oauth_shiny_ui_button` which can be used in the login UI (dark
#'   theme)
#' @param login_path Endpoint where users will be redirected to login for the
#'   client, e.g. `/login/github`. Typically not overridden.
#' @param logout_path Endpoint where users will be redirected to login for the
#'   client, e.g. `/logout/github` Typically not overridden.
#' @param client_cookie_name The name of the client cookie which contains the
#'   access_token (and potentially id_token) for the client
#' @param access_token_validity Validity duration for the client cookie which
#'   contains the access token. If you want to make the client token available
#'   in the application, set this to a value > `0`, e.g. `3600`. If set to
#'   `NULL` the cookie will have the same validity as the token if specified and
#'   will be unavailable if the token does not contain an expiry time (e.g.
#'   Github). Regardless of the value set, the cookie will not expire later than
#'   the token itself expires
#' @export
oauth_shiny_client <- function(
    name,
    id,
    secret = NULL,
    auth_url = NULL,
    token_url = NULL,
    redirect_uri = oauth_redirect_uri(),
    openid_issuer_url = NULL,
    openid_claims = c("aud", "sub", "name", "email"),
    scope = NULL,
    auth_params = list(),
    token_params = list(),
    pkce = TRUE,
    postprocess_token = NULL,
    auth_provider = FALSE,
    auth_provider_primary = FALSE,
    auth_set_custom_claim = NULL,
    login_button = NULL,
    login_button_dark = NULL,
    login_path = paste0("login/", name),
    logout_path = paste0("logout/", name),
    client_cookie_name = paste0("oauth_app_", name, "_token"),
    access_token_validity = 0) {
  if (!grepl("^[a-zA-Z][a-zA-Z0-9_]*$", name)) {
    cli::cli_abort("{.arg name} should only contain letters and underscores")
  }
  if (is.null(auth_url) & is.null(openid_issuer_url)) {
    cli::cli_abort("OAuth Client requires either {.arg auth_url} or {.arg openid_issuer_url}")
  }
  if (is.null(token_url) & is.null(openid_issuer_url)) {
    cli::cli_abort("OAuth Client requires either {.arg token_url} or {.arg openid_issuer_url}")
  }

  structure(
    list(
      name = name,
      id = id,
      secret = secret,
      auth_url = auth_url,
      token_url = token_url,
      redirect_uri = redirect_uri,
      openid_issuer_url = openid_issuer_url,
      openid_claims = openid_claims,
      scope = scope,
      auth_params = auth_params,
      token_params = token_params,
      pkce = pkce,
      postprocess_token = postprocess_token,
      auth_provider = auth_provider,
      auth_provider_primary = auth_provider_primary,
      auth_set_custom_claim = auth_set_custom_claim,
      login_button = login_button,
      login_button_dark = login_button_dark,
      login_path = login_path,
      logout_path = logout_path,
      client_cookie_name = client_cookie_name,
      access_token_validity = access_token_validity
    ),
    class = "httr2_oauth_shiny_client"
  )
}

#' @export
print.httr2_oauth_shiny_client <- function(x, ...) {
  cli::cli_text(cli::style_bold("<", paste(class(x), collapse = "/"), ">"))
  redacted <- list_redact(compact(x), c("secret", "key"))
  redacted <- redacted[map_lgl(redacted, is.atomic)]
  cli::cli_dl(redacted)
  invisible(x)
}

#' Configure Multiple OAuth Shiny Clients
#'
#' This function allows you to configure multiple OAuth Shiny Clients by
#' combining them into a single list. This is useful when your Shiny application
#' supports multiple OAuth providers (e.g., Google, Microsoft, GitHub, etc.).
#'
#' Each client in the list must be an object created by the
#' `oauth_shiny_client()` function or one of its specialized versions (e.g.,
#' `oauth_shiny_client_google()`).
#'
#' @param ... A series of OAuth Shiny Client objects created by
#'   `oauth_shiny_client()` or its specialized versions.
#'
#' @return A named list of OAuth Shiny Client objects. The names of the list
#'   elements correspond to the `name` parameter of each client.
#'
#' @examples
#' \dontrun{
#' google_client <- oauth_shiny_client_google()
#' microsoft_client <- oauth_shiny_client_microsoft()
#' config <- oauth_shiny_client_config(google_client, microsoft_client)
#' }
#'
#' @export
oauth_shiny_client_config <- function(...) {
  is_oauth_shiny_client <- function(x) class(x) == "httr2_oauth_shiny_client"
  if (!all(map_lgl(list(...), is_oauth_shiny_client))) {
    cli::cli_abort("Input to {.fun oauth_shiny_client_config} must be a list
                   of clients generated by {.fun oauth_shiny_client}")
  }
  set_names(list(...), map(list(...), function(client) client$name))
}


#' Create an OAuth Shiny Client for Microsoft
#'
#' This function creates an OAuth Shiny Client specifically for Microsoft. It
#' uses the general `oauth_shiny_client` function to set up the client with
#' Microsoft-specific defaults.
#'
#' For parameter details, see [oauth_shiny_client()].
#'
#' @param name The name of the OAuth Provider, default is "microsoft".
#' @param id Client ID, defaults to environment variable
#'   `OAUTH_MICROSOFT_CLIENT_ID`.
#' @param secret Client Secret, defaults to environment variable
#'   `OAUTH_MICROSOFT_CLIENT_SECRET`.
#' @param openid_issuer_url URL for OpenID issuer.
#' @param scope Scopes to be requested, defaults to "openid profile email".
#' @param login_button Button used for Microsoft login, defaults to
#'   `oauth_shiny_ui_button_microsoft()`.
#' @param login_button_dark Dark theme button for Microsoft login, defaults to
#'   `oauth_shiny_ui_button_microsoft_dark()`.
#' @param ... Additional arguments passed to `oauth_shiny_client()`.
#'
#' @return A Shiny OAuth Client configured for Microsoft.
#' @export
#'
#' @examples
#' \dontrun{
#' microsoft_client <- oauth_shiny_client_microsoft()
#' }
#'
oauth_shiny_client_microsoft <- function(
    name = "microsoft",
    id = Sys.getenv("OAUTH_MICROSOFT_CLIENT_ID"),
    secret = Sys.getenv("OAUTH_MICROSOFT_CLIENT_SECRET"),
    openid_issuer_url,
    scope = "openid profile email",
    login_button = oauth_shiny_ui_button_microsoft(),
    login_button_dark = oauth_shiny_ui_button_microsoft_dark(),
    ...) {
  oauth_shiny_client(
    name = name,
    id = id,
    secret = secret,
    openid_issuer_url = openid_issuer_url,
    scope = scope,
    login_button = login_button,
    login_button_dark = login_button_dark,
    ...
  )
}

#' Create an OAuth Shiny Client for Google
#'
#' This function creates an OAuth Shiny Client specifically for Google. It uses
#' the general `oauth_shiny_client` function to set up the client with
#' Google-specific defaults.
#'
#' For parameter details, see [oauth_shiny_client()].
#'
#' @param name The name of the OAuth Provider, default is "google".
#' @param id Client ID, defaults to environment variable
#'   `OAUTH_GOOGLE_CLIENT_ID`.
#' @param secret Client Secret, defaults to environment variable
#'   `OAUTH_GOOGLE_CLIENT_SECRET`.
#' @param openid_issuer_url URL for OpenID issuer, defaults to
#'   "https://accounts.google.com/".
#' @param scope Scopes to be requested, defaults to "openid profile email".
#' @param login_button Button used for Google login, defaults to
#'   `oauth_shiny_ui_button_google()`.
#' @param login_button_dark Dark theme button for Google login, defaults to
#'   `oauth_shiny_ui_button_google_dark()`.
#' @param ... Additional arguments passed to `oauth_shiny_client()`.
#'
#' @return A Shiny OAuth Client configured for Google.
#' @export
#'
#' @examples
#' \dontrun{
#' google_client <- oauth_shiny_client_google()
#' }
#'
oauth_shiny_client_google <- function(
    name = "google",
    id = Sys.getenv("OAUTH_GOOGLE_CLIENT_ID"),
    secret = Sys.getenv("OAUTH_GOOGLE_CLIENT_SECRET"),
    openid_issuer_url = "https://accounts.google.com/",
    scope = "openid profile email",
    login_button = oauth_shiny_ui_button_google(),
    login_button_dark = oauth_shiny_ui_button_google_dark(),
    ...) {
  oauth_shiny_client(
    name = name,
    id = id,
    secret = secret,
    openid_issuer_url = openid_issuer_url,
    scope = scope,
    login_button = login_button,
    login_button_dark = login_button_dark,
    ...
  )
}

#' Create a Github OAuth Client in Shiny
#'
#' This function creates an OAuth Shiny Client specifically for GitHub. It uses
#' the general `oauth_shiny_client` function to set up the client with
#' GitHub-specific defaults. Note that Github does not currently support openid,
#' hence it requires additional requests to `/user/email` to authorize the user.
#' Create the app from your [Developer
#' Settings](https://github.com/settings/developers)
#'
#' @param name The name of the OAuth Provider, default is "github".
#' @param id Client ID, defaults to environment variable
#'   `OAUTH_GITHUB_CLIENT_ID`.
#' @param secret Client Secret, defaults to environment variable
#'   `OAUTH_GITHUB_CLIENT_SECRET`.
#' @param redirect_uri Authorization callback URL, defaults to
#'   `oauth_redirect_uri()`.
#' @param scope Scopes to be requested, defaults to "read:user user:email".
#' @param login_button Button used for GitHub login, defaults to
#'   `oauth_shiny_ui_button_github()`.
#' @param login_button_dark Dark theme button for GitHub login, defaults to
#'   `oauth_shiny_ui_button_github_dark()`.
#' @param auth_set_custom_claim Custom function for setting claims, defaults
#'   to `oauth_shiny_client_github_set_custom_claim`.
#' @param ... Additional arguments passed to `oauth_shiny_client()`.
#'
#' @return A Shiny OAuth Client configured for GitHub.
#' @export
#'
#' @examples
#' \dontrun{
#' spotify_client <- oauth_shiny_client_spotify()
#' }
#'
oauth_shiny_client_github <- function(
    name = "github",
    id = Sys.getenv("OAUTH_GITHUB_CLIENT_ID"),
    secret = Sys.getenv("OAUTH_GITHUB_CLIENT_SECRET"),
    redirect_uri = oauth_redirect_uri(),
    scope = "read:user user:email",
    login_button = oauth_shiny_ui_button_github(),
    login_button_dark = oauth_shiny_ui_button_github_dark(),
    auth_set_custom_claim = oauth_shiny_client_github_set_custom_claim,
    ...) {
  oauth_shiny_client(
    name = name,
    id = id,
    secret = secret,
    auth_url = "https://github.com/login/oauth/authorize",
    token_url = "https://github.com/login/oauth/access_token",
    pkce = FALSE,
    redirect_uri = redirect_uri,
    scope = scope,
    login_button = login_button,
    login_button_dark = login_button_dark,
    auth_set_custom_claim = auth_set_custom_claim,
    ...
  )
}

#' This function creates an OAuth Shiny Client specifically for Spotify. It uses
#' the general `oauth_shiny_client` function to set up the client with
#' Spotify-specific defaults.
#'
#' For parameter details, see [oauth_shiny_client()].
#'
#' @param name The name of the OAuth Provider, default is "spotify".
#' @param id Client ID, defaults to environment variable
#'   `OAUTH_SPOTIFY_CLIENT_ID`.
#' @param secret Client Secret, defaults to environment variable
#'   `OAUTH_SPOTIFY_CLIENT_SECRET`.
#' @param redirect_uri Authorization callback URL, defaults to
#'   `oauth_redirect_uri()`.
#' @param scope Scopes to be requested, defaults to "user-read-email".
#' @param login_button Button used for Spotify login, defaults to
#'   `oauth_shiny_ui_button_spotify()`.
#' @param login_button_dark Dark theme button for Spotify login, defaults to
#'   `oauth_shiny_ui_button_spotify_dark()`.
#' @param auth_set_custom_claim Custom function for setting claims, defaults
#'   to `oauth_shiny_client_spotify_set_custom_claim`.
#' @param ... Additional arguments passed to `oauth_shiny_client()`.
#'
#' @return A Shiny OAuth Client configured for Spotify.
#' @export
#'
#' @examples
#' \dontrun{
#' spotify_client <- oauth_shiny_client_spotify()
#' }
oauth_shiny_client_spotify <- function(
    name = "spotify",
    id = Sys.getenv("OAUTH_SPOTIFY_CLIENT_ID"),
    secret = Sys.getenv("OAUTH_SPOTIFY_CLIENT_SECRET"),
    redirect_uri = oauth_redirect_uri(),
    scope = "user-read-email",
    login_button = oauth_shiny_ui_button_spotify(),
    login_button_dark = oauth_shiny_ui_button_spotify_dark(),
    auth_set_custom_claim = oauth_shiny_client_spotify_set_custom_claim,
    ...) {
  oauth_shiny_client(
    name = name,
    id = id,
    secret = secret,
    auth_url = "https://accounts.spotify.com/authorize",
    token_url = "https://accounts.spotify.com/api/token",
    pkce = TRUE,
    redirect_uri = redirect_uri,
    scope = scope,
    login_button = login_button,
    login_button_dark = login_button_dark,
    auth_set_custom_claim = auth_set_custom_claim,
    ...
  )
}

#' Set Custom Claims for GitHub OAuth Client
#'
#' This function retrieves user information from GitHub and sets custom claims
#' for the OAuth token. The claims include the user's primary email and name.
#'
#' This function is typically used with the GitHub OAuth client created by
#' `oauth_shiny_client_github`.
#'
#' @param client An OAuth Shiny Client object created by
#'   `oauth_shiny_client_github`.
#' @param token The OAuth token object containing `access_token`.
#'
#' @return A list of custom claims, including `sub` (email), `name` (user's
#'   name), and `provider` (provider name, "github.com").
#' @export
#'
#' @examples
#' \dontrun{
#' claims <- oauth_shiny_client_github_set_custom_claim(client, token)
#' }
#'
oauth_shiny_client_github_set_custom_claim <- function(client, token) {
  req <- request("https://api.github.com/user/emails")
  req <- req_auth_bearer_token(req, token$access_token)
  req <- req_perform(req)
  resp <- resp_body_json(req)

  email_primary_idx <- which(as.logical(lapply(resp, function(x) x$primary)))
  email <- resp[[email_primary_idx]][["email"]]

  req <- request("https://api.github.com/user")
  req <- req_auth_bearer_token(req, token$access_token)
  req <- req_perform(req)
  resp <- resp_body_json(req)
  name <- resp$name

  claims <- list(
    sub = email,
    aud = "github.com",
    name = name
  )
  claims
}

#' Set Custom Claims for Spotify OAuth Client
#'
#' This function retrieves user information from Spotify and sets custom claims
#' for the OAuth token. The claims include the user's email and display name.
#'
#' This function is typically used with the Spotify OAuth client created by
#' `oauth_shiny_client_spotify`.
#'
#' @param client An OAuth Shiny Client object created by
#'   `oauth_shiny_client_spotify`.
#' @param token The OAuth token object containing `access_token`.
#'
#' @return A list of custom claims, including `sub` (email), `aud` (audience,
#'   "spotify.com"), and `name` (display name).
#' @export
#'
#' @examples
#' \dontrun{
#' # Assuming `spotify_client` is created with `oauth_shiny_client_spotify()`
#' claims <- oauth_shiny_client_spotify_set_custom_claim(spotify_client, token)
#' }
#'
oauth_shiny_client_spotify_set_custom_claim <- function(client, token) {
  req <- request("https://api.spotify.com/v1/me")
  req <- req_auth_bearer_token(req, token$access_token)
  req <- req_perform(req)
  resp <- resp_body_json(req)

  claims <- list(
    sub = resp$email,
    aud = "spotify.com",
    name = resp$display_name
  )
  claims
}
